version: '2'

services:
  symfony_kindle:
    container_name: symfony_kindle
    image: webdevops/php-apache-dev:7.2
    links:
      - symfony_kindle_mysql
      - symfony_kindle_mysql_test
    depends_on:
      - symfony_kindle_mysql
      - symfony_kindle_mysql_test
    ports:
      - 8458:443
    volumes:
      - .:/app
      - /reports/coverage:/app/reports/coverage
    environment:
      docker: 'true'
      WEB_DOCUMENT_ROOT: '/app/public'
      WEB_NO_CACHE_PATTERN: '\.(.*)$$'
      working_dir: '/app'
  symfony_kindle_mysql:
    image: mariadb:latest
    ports:
      - 3332:3332
    environment:
      MYSQL_ROOT_PASSWORD: 'dev'
      MYSQL_DATABASE: 'dev'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
  symfony_kindle_mysql_test:
    image: mariadb:latest
    ports:
      - 3333:3333
    environment:
      MYSQL_ROOT_PASSWORD: 'dev'
      MYSQL_DATABASE: 'dev'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      links:
        - symfony_kindle_mysql
      ports:
        - 8091:80
      environment:
        - PMA_ARBITRARY=1
        - VIRTUAL_HOST=pma.boilerplate.docker
        - VIRTUAL_PORT=80
      volumes:
        - /sessions
  phpmyadmin_test:
      image: phpmyadmin/phpmyadmin
      links:
        - symfony_kindle_mysql_test
      ports:
        - 8092:80
      environment:
        - PMA_ARBITRARY=1
        - VIRTUAL_HOST=pma.boilerplate.docker
        - VIRTUAL_PORT=80
      volumes:
        - /sessions