version: '3'

services:
  symfony_kindle_nginx:
    image: nginx:alpine
    container_name: symfony_kindle_nginx
    ports:
      - "8111:80"
    volumes:
      - .:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony_kindle_php

  symfony_kindle_php:
    build: ./.docker
    container_name: symfony_kindle_php
    working_dir: /var/www
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - .:/var/www
      - ./.docker/exec-time.ini:/usr/local/etc/php/conf.d/docker-exec-time.ini
    #      - ./.docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "9111:9111"
    depends_on:
      - symfony_kindle_mysql

  symfony_kindle_mysql:
    image: mariadb:10.5
    ports:
      - "3315:3315"
    environment:
      MYSQL_DATABASE: symfony_kindle
      MYSQL_USER: symfony_kindle
      MYSQL_PASSWORD: pwdpwd
      MYSQL_ROOT_PASSWORD: pwdpwd
    volumes:
      - sk_dbdata:/var/lib/mysql

  symfony_kindle_mysql_test:
    image: mariadb:10.5
    ports:
      - "3316:3316"
    environment:
      MYSQL_DATABASE: symfony_kindle_test
      MYSQL_USER: symfony_kindle
      MYSQL_PASSWORD: pwdpwd
      MYSQL_ROOT_PASSWORD: pwdpwd

  symfony_kindle_phpmyadmin:
      image: phpmyadmin
      links:
        - symfony_kindle_mysql
      ports:
        - 8200:80
      environment:
        - PMA_HOST=symfony_kindle_mysql
        - VIRTUAL_HOST=pma.boilerplate.docker
        - VIRTUAL_PORT=80
      volumes:
        - /sessions

  symfony_kindle_phpmyadmin_test:
      image: phpmyadmin
      links:
        - symfony_kindle_mysql_test
      ports:
        - 8201:80
      environment:
        - PMA_HOST=symfony_kindle_mysql_test
        - VIRTUAL_HOST=pma.boilerplate.docker
        - VIRTUAL_PORT=80
      volumes:
        - /sessions

  # This automatically stops when I run docker-compose up. Look into this.
  # For now, to run a command, run `docker-compose run --rm node <npm command>`
  node:
    image: node:13 # I tried `latest` but npm spat some errors at me when I tried to run it
    volumes:
      - .:/var/www
    working_dir: /var/www
    entrypoint: [ 'npm' ]

volumes:
  sk_dbdata: